name: Run tests
on: [push]
jobs:
  run-bazel-test:
    runs-on: ubuntu-latest
    steps:
      - run: bazel test //...
    # runs-on: gcr.io/bazel-public/bazel:7.3.2
    # steps:
    #   - run: test ...
