name: Run tests
on: [push]
jobs:
  run-bazel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - uses: actions/checkout@v2
      - run: bazel test //...
    # runs-on: gcr.io/bazel-public/bazel:7.3.2
    # steps:
    #   - run: test ...
